# Generated by Django 5.2.1 on 2025-05-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='../profile'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
