# Generated by Django 5.2 on 2025-05-18 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_document_original_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('pdf_data', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(choices=[('cs', 'Computer Science'), ('medicine', 'Medicine'), ('physics', 'Physics')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structured_outline', models.JSONField(help_text='Hierarchical outline with sections')),
                ('key_definitions', models.JSONField(help_text='Glossary of terms')),
                ('critical_quotes', models.TextField(blank=True)),
                ('tl_dr', models.TextField(help_text='One-paragraph summary')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='api.book')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
