# Generated by Django 5.2 on 2025-05-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_book_booksummary_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='domain',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('medicine', 'Medicine'), ('physics', 'Physics'), ('religion', 'Religion')], max_length=100),
        ),
    ]
