# Generated by Django 5.2 on 2025-05-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_book_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksummary',
            name='critical_quotes',
        ),
        migrations.RemoveField(
            model_name='booksummary',
            name='key_definitions',
        ),
        migrations.RemoveField(
            model_name='booksummary',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='booksummary',
            name='structured_outline',
        ),
        migrations.RemoveField(
            model_name='booksummary',
            name='tl_dr',
        ),
        migrations.AddField(
            model_name='booksummary',
            name='headings',
            field=models.JSONField(default={'default': 'defaultValue'}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booksummary',
            name='markdown',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booksummary',
            name='page_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
