# Generated by Django 5.2 on 2025-05-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_booksummary_critical_quotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='domain',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('medicine', 'Medicine'), ('physics', 'Physics'), ('religion', 'Religion'), ('ph', 'Philosophy'), ('math', 'Mathematics'), ('history', 'History'), ('art', 'Art'), ('other', 'Other')], max_length=100),
        ),
    ]
