# Generated by Django 5.2 on 2025-05-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_book_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksummary',
            name='headings',
        ),
        migrations.AddField(
            model_name='booksummary',
            name='key_terms',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='booksummary',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booksummary',
            name='model_used',
            field=models.CharField(default='deepseek-chat', max_length=100),
        ),
        migrations.AddField(
            model_name='booksummary',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booksummary',
            name='sections',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='booksummary',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booksummary',
            name='markdown',
            field=models.TextField(blank=True),
        ),
    ]
