# Generated by Django 5.2 on 2025-05-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customuser_image'),
        ('api', '0010_remove_booksummary_headings_booksummary_key_terms_and_more'),
    ]

    operations = [
    ]
