# Generated by Django 5.2.1 on 2025-05-30 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20250530_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookContent',
            fields=[
                ('notebook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='content_object', serialize=False, to='api.notebook')),
                ('markdown_content', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='domain',
        ),
        migrations.AddField(
            model_name='book',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.notebook'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notebook',
            name='color',
            field=models.CharField(default='#FFD25E', max_length=20),
        ),
        migrations.AddField(
            model_name='notebook',
            name='mastery_goal',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
