# Generated by Django 5.2 on 2025-05-29 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_book_domain_book_notebook_book_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookContent',
            fields=[
                ('notebook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='content_object', serialize=False, to='api.notebook')),
                ('markdown_content', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
