# Generated by Django 5.2 on 2025-05-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_notebookcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='color',
            field=models.CharField(default='#FFD25E', max_length=20),
        ),
        migrations.AddField(
            model_name='notebook',
            name='mastery_goal',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
