# Generated by Django 5.2 on 2025-06-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20250529_1832'),
        ('api', '0014_notebook_color_notebook_mastery_goal'),
    ]

    operations = [
    ]
