# Generated by Django 5.2 on 2025-06-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20250530_1558'),
        ('api', '0012_notebookcontent_remove_book_domain_book_notebook_and_more'),
    ]

    operations = [
    ]
