# Generated by Django 5.2 on 2025-06-04 13:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20250603_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity_heatmap',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PinnedNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Order of the pinned notebook (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.notebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='pinned_notebooks',
            field=models.ManyToManyField(related_name='pinned_by_users', through='api.PinnedNotebook', to='api.notebook'),
        ),
        migrations.AddConstraint(
            model_name='pinnednotebook',
            constraint=models.UniqueConstraint(fields=('user', 'order'), name='unique_user_order_pinned_notebook'),
        ),
        migrations.AlterUniqueTogether(
            name='pinnednotebook',
            unique_together={('user', 'notebook')},
        ),
    ]
