# Generated by Django 5.2 on 2025-06-04 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_customuser_activity_heatmap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostItNote',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='post_it_note', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(blank=True, default='Untitled Note', max_length=100)),
                ('text_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
