# Generated by Django 5.2 on 2025-06-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_postitnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postitnote',
            name='text_content',
            field=models.TextField(default=''),
        ),
    ]
